name: govendor
version: git
summary: A dependency vendoring tool for Go development.
description: >
  govendor helps maintains Go dependencies and vendoring. See
  https://github.com/kardianos/govendor for details.
type: app
confinement: classic
grade: stable
version-script: |
  git -C parts/govendor/src describe --tags --always
apps:
  govendor:
    command: bin/govendor
parts:
  govendor:
    plugin: go
    go-importpath: github.com/kardianos/govendor
    source: https://github.com/kardianos/govendor
    source-type: git

    # No tag, for building trunk to edge channel.
    # source-tag: v1.0.8
